name: Build/release

on:
  push:
   branches:
     - master

jobs:
  build_on_win:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.19
      - run: npm ci
      - run: npm run build
      - run: npm run compile

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            releases/Luna_QMapEditor-win.zip
            releases/Luna_QMapEditor-win-setup.exe

      - name: Upload to release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          title: "Nightly Build"
          prerelease: true
          files: |
            releases/Luna_QMapEditor-win.zip
            releases/Luna_QMapEditor-win-setup.exe
            releases/Luna_QMapEditor-linux.zip
            releases/Luna_QMapEditor-mac.zip